M48
; DRILL file KiCad 10.0.4 date 2026-09-25T19:22:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T19:22:45+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X78.325Y-113.15
X85.125Y-113.15
T2
X68.85Y-89.85
X94.7Y-89.85
X120.45Y-89.85
X131.125Y-110.15
T3
X71.5Y-100.0
X128.5Y-100.0
M30
