M48
; DRILL file KiCad 10.0.4 date 2026-07-29T13:13:46
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-29T13:13:46+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.700
%
G90
G05
T1
X77.9Y-111.825
X84.7Y-111.825
T2
X68.85Y-91.1
X94.325Y-91.1
X120.45Y-91.1
X131.15Y-108.9
T3
X71.5Y-100.0
X128.5Y-100.0
M30
