M48
; DRILL file KiCad 10.0.4 date 2026-07-25T01:45:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-25T01:45:00+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X84.0Y-93.0
X90.8Y-93.0
T2
X58.0Y-58.0
X58.0Y-97.0
X97.0Y-58.0
X97.0Y-97.0
M30
